### ISSUE TITLE
Row & Column Totals

### ISSUE THREAD

**Issue by zheath** [turnerniles/react-virtualized-pivot#100]
I'm pretty new to programming, especially in meteor/react and this package is awesome - super light weight, easy to install and implement - thank you! 

I was wondering if you have any plans to support row and column totals?

**Comment by turnerniles** [comment]
Hi @zheath, yes we do plan to add it. We have an open issue on the quick-pivot engine to add the row and column totals [here](https://github.com/pat310/quick-pivot/issues/53). Once implemented in the quick-pivot it will be easy to add to react-virtualized-pivot. Will get back to you on timing shortly.

**Comment by turnerniles** [comment]
Closed by accident.

**Comment by pat310** [comment]
@zheath @turnerniles have a [PR open](https://github.com/pat310/quick-pivot/pull/62) for row aggregation across the entire table (i.e. one row at the bottom that contains the aggregated values of all the rows in each column) based on the selected aggregation function. I'll get the column aggregation in a different PR.

**Comment by turnerniles** [comment]
@zheath @turnerniles please see #104. Will merge shortly.

**Comment by turnerniles** [comment]
@zheath @pat310 Row totals are live.

**Comment by pat310** [comment]
@turnerniles Almost have a [PR ready](https://github.com/pat310/quick-pivot/pull/67) for column totals

**Comment by turnerniles** [comment]
@pat310 @zheath See #105 will merge shortly...
