### ISSUE TITLE
Add CSV/TSV Format Checker To Demo 

### ISSUE THREAD

**Issue by scottcarol** [turnerniles/react-virtualized-pivot#106]
Great project - thanks.

When a user is first accessing the [demo](https://turnerniles.github.io/react-virtualized-pivot/), they may not understand that the "Choose File" button is for a CSV/TSV file with headers.

What do you think of a pull request for the following changes?

- Change wording of button on demo page from "Choose File" to "Upload CSV/TSV File"
- Once CSV/TSV file is uploaded, preview the first row and confirm with user that these are the headers. If not, user can add headers and this will be added to the data as first row.

**Comment by pat310** [comment]
@niles 👆

**Comment by scottcarol** [comment]
Hey @patt310 - did you mean to flag for @turnerniles?

**Comment by pat310** [comment]
Whoops, yup! Thanks

**Comment by turnerniles** [comment]
@scottcarol @pat310 I would definitely accept a PR for that!

**Comment by scottcarol** [comment]
@turnerniles @pat310 Awesome! I'll ping this thread when I have a PR for your review.
