### ISSUE TITLE
Add color schemes to Pivot component

### ISSUE THREAD

**Issue by turnerniles** [turnerniles/react-virtualized-pivot#11]
Pivot should receive a color scheme property that is an object where each key references the part of the component and the value is a color. Then in the Pivot code all of the colors should then reference this object instead of the current hard coding. We can also create two default themes, the current color theme and another more professional theme.

**Comment by turnerniles** [comment]
@jaredwent I've added a colorpack property. Now we just need to add a new colorpack! https://github.com/turnerniles/react-virtualized-pivot/blob/master/src/app.jsx#L75-L91

**Comment by turnerniles** [comment]
@jaredwent, @pat310 may have to take over this issue.

**Comment by pat310** [comment]
@jaredwent may the best man win

**Comment by turnerniles** [comment]
@jaredwent what's the status on this priority ticket?

**Comment by turnerniles** [comment]
@jaredwent it is done.
