### ISSUE TITLE
Callback for cell display value

### ISSUE THREAD

**Issue by pat310** [turnerniles/react-virtualized-pivot#43]
As a user, I expect to be able to provide a `bodyCellValue` prop that accepts a callback function which supplies the current cell value as a parameter.  I can then adjust how the value is displayed via javascript, which may be useful for things like rounding and number formatting.

**Comment by pat310** [comment]
@turnerniles I noticed you closed this but I don't see this as an available prop type.  Did you close this by accident or do you not want me to do it anymore?

**Comment by turnerniles** [comment]
@pat310 closed by mistake!
