### ISSUE TITLE
Add gif to README

### ISSUE THREAD

**Issue by pat310** [turnerniles/react-virtualized-pivot#53]
As a user, it would be helpful to have a gif of the library in action directly in the README so I don't have to go to the demo to see roughly what it does.

**Comment by pat310** [comment]
@jaredwent this should be done after #49 is complete by @turnerniles

**Comment by pat310** [comment]
@jaredwent may the best man win

**Comment by pat310** [comment]
[guide](https://gist.github.com/paulirish/b6cf161009af0708315c)

**Comment by pat310** [comment]
![pivot_demo](https://user-images.githubusercontent.com/12212504/29735594-03aa740c-89c8-11e7-83c3-3d59c14d910e.gif)

**Comment by turnerniles** [comment]
![image](https://user-images.githubusercontent.com/8146241/29742790-5de06522-8a53-11e7-9304-5413d45641e8.png)

**Comment by turnerniles** [comment]
![pivot_gif](https://user-images.githubusercontent.com/8146241/29742823-06c2adf8-8a54-11e7-96ed-18466e853482.gif)
